### ISSUE TITLE
Thank you very much !!!

### ISSUE THREAD

**Issue by MrShtein** [itsjamie/realtime-games#27]
Good afternoon, Jamie, sorry to clutter this issue, but I have not found another way to say thank you for the answer to my issue in hls.js

**Comment by itsjamie** [comment]
No problem :).

**Comment by MrShtein** [comment]
And if suddenly I have any questions on hls.js maybe you have them somewhere to ask. Maybe e-mail ? If of course You will have time.

**Comment by itsjamie** [comment]
If you give me an e-mail, I can invite you to the video-dev Slack group. There is a hlsjs channel there you can ask questions in and more folks can help too :+1:

**Comment by MrShtein** [comment]
It's ok. Thank you. mr.shtein@outlook.com

**Comment by itsjamie** [comment]
Looks like you already have an account at video-dev.slack.com with that email. You should be able to get on there.

**Comment by MrShtein** [comment]
This is very strange)) I will try to recover the password. I guess I once registered and forgot about it.
